import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { builtinModules } from "node:module";

const isWatch = process.argv.includes("--watch");

const concatStyles = () => {
  const xyflowPath = path.join(
    "node_modules",
    "@xyflow",
    "react",
    "dist",
    "style.css",
  );
  const xyflowCss = fs.existsSync(xyflowPath)
    ? fs.readFileSync(xyflowPath, "utf8")
    : "/* @xyflow/react CSS not found at build time */";
  const ourCss = fs.readFileSync("styles.src.css", "utf8");
  fs.writeFileSync(
    "styles.css",
    [
      "/* mermaid-gui-editor — generated by esbuild.config.mjs (do not edit by hand) */",
      "/* @xyflow/react styles (vendored) */",
      xyflowCss,
      "",
      "/* mermaid-gui-editor own styles */",
      ourCss,
    ].join("\n"),
  );
};

const ctx = await esbuild.context({
  entryPoints: ["main.ts"],
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: "es2020",
  jsx: "automatic",
  loader: { ".css": "empty" },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  outfile: "main.js",
  sourcemap: isWatch ? "inline" : false,
  minify: !isWatch,
  treeShaking: true,
  logLevel: "info",
  banner: {
    js: `/* mermaid-gui-editor — built ${new Date().toISOString()} */`,
  },
});

concatStyles();

if (isWatch) {
  console.log("[esbuild] watching main.ts and styles.src.css …");
  await ctx.watch();
  // Re-concat styles when the source CSS changes.
  fs.watch("styles.src.css", () => {
    try {
      concatStyles();
      console.log("[esbuild] styles.css refreshed");
    } catch (err) {
      console.error("[esbuild] style concat failed:", err);
    }
  });
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log("[esbuild] build complete → main.js + styles.css");
}
